// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {context} from '../models';

export function AddApp(arg1:string,arg2:string,arg3:string):Promise<config.App>;

export function GetApps():Promise<Array<config.App>>;

export function GetContext():Promise<context.Context>;

export function GetProcessStatuses():Promise<Record<string, boolean>>;

export function GetServerInfo():Promise<Record<string, any>>;

export function Hide():Promise<void>;

export function IsServerRunning():Promise<boolean>;

export function IsWindowVisible():Promise<boolean>;

export function LaunchApp(arg1:string):Promise<void>;

export function RemoveApp(arg1:string):Promise<void>;

export function SelectFile():Promise<string>;

export function SetQuitting(arg1:boolean):Promise<void>;

export function Show():Promise<void>;

export function StartServer():Promise<void>;

export function StopServer():Promise<void>;

export function UpdateApp(arg1:string,arg2:string,arg3:string,arg4:string):Promise<boolean>;
