// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddApp(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddApp'](arg1, arg2, arg3);
}

export function GetApps() {
  return window['go']['main']['App']['GetApps']();
}

export function GetServerInfo() {
  return window['go']['main']['App']['GetServerInfo']();
}

export function LaunchApp(arg1) {
  return window['go']['main']['App']['LaunchApp'](arg1);
}

export function RemoveApp(arg1) {
  return window['go']['main']['App']['RemoveApp'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function UpdateApp(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateApp'](arg1, arg2, arg3, arg4);
}
