name: Release App

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build Application
        working-directory: ./aviator-wails
        run: |
          wails build -platform windows/amd64 -clean

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: aviator-wails/build/bin/aviator-wails.exe
          token: ${{ secrets.GITHUB_TOKEN }}
